version: '3.4'

services:
  knab.exchange.api:
    container_name: knab.exchange.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1900:80"

  knab.identity.api:
    container_name: knab.identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1901:80"

  knab.exchange.ui:
    container_name: knab.exchange.ui
    volumes:
      - 'ui-data:/app'
      - '/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start


  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw